/**
 * Fitness Tips widget — Claude generates activity-specific fitness tips
 * based on calendar events detected as fitness-related (walk, yoga, weights, etc.).
 *
 * Runs after calendar widget (order 55) using context, so calendar data is already fetched.
 * Opt-in (defaultEnabled: false) — user must enable in CONFIG.
 *
 * BYOK: uses the user's Claude API key (Haiku by default — fast and cheap).
 */
import { complete } from '../lib/claude.js';
import { t } from '../lib/i18n.js';

const FITNESS_KEYWORDS = [
  'walk', 'run', 'jog', 'yoga', 'weights', 'gym',
  'workout', 'pilates', 'swim', 'bike', 'cycle', 'hike', 'stretch', 'lift',
  'crossfit', 'spin', 'cardio', 'training', 'exercise', 'fitness', 'hiit',
  'tennis', 'golf', 'dance', 'zumba', 'rowing', 'climbing'
];

const SYSTEM = `You are a friendly fitness coach. Your job is to provide 1-3 brief, practical tips
related to the user's scheduled fitness activities. Be specific and encouraging.
Format as a simple bulleted list. No intro text, no markdown formatting, just the bullets.
Keep each tip to 1-2 sentences max.`;

export default {
  id: 'fitness-tips',
  name: 'Fitness Tips',
  requiredKeys: ['claude'],
  defaultEnabled: false,
  needsContext: true,   // fetch(config, sitrepContext) — runs after base widgets
  order: 55,

  /**
   * @param {object} config  — full BROVIS config
   * @param {object} context — sitrep data including calendar events
   */
  async fetch(config, context = {}) {
    // Check if calendar auth is needed
    if (context.calendar?.needsAuth) {
      return t('widget.fitness.connectcal');
    }

    // Get calendar events, default to empty if not available
    const events = context.calendar?.events ?? [];
    if (events.length === 0) {
      return t('widget.fitness.noevents');
    }

    // Filter for fitness-related events (case-insensitive)
    const fitnessEvents = events.filter(e =>
      FITNESS_KEYWORDS.some(kw => e.title.toLowerCase().includes(kw.toLowerCase()))
    );

    if (fitnessEvents.length === 0) {
      return t('widget.fitness.nofitness');
    }

    // Build activity list for Claude
    const activities = fitnessEvents.map(e => e.title).join(', ');
    const prompt = `Today's fitness activities: ${activities}.\n\nGive me 1-3 practical tips or article ideas related to these specific activities.`;

    return complete({
      system: SYSTEM,
      prompt,
      maxTokens: 300,
      temperature: 0.7,
      cacheSystemPrompt: true
    });
  },

  render(text) {
    return `
      <div class="sitrep-section fitness-tips">
        <div class="sitrep-section-title">
          ${t('widget.fitness.name')}
          <span class="claude-badge" title="Generated by Claude · Anthropic">
            <svg class="claude-icon" viewBox="0 0 24 24" aria-hidden="true">
              <path d="M13.827 3.52l8.123 14.069a1.45 1.45 0 0 1-1.256 2.179H3.306a1.45 1.45 0 0 1-1.256-2.179L10.173 3.52a1.946 1.946 0 0 1 3.654 0z"/>
            </svg>
            Claude
          </span>
        </div>
        <p class="brief-text">${escapeHtml(text)}</p>
      </div>
    `;
  }
};

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}
