/**
 * Morning Brief widget — Claude synthesizes weather, news, markets, and
 * calendar into a concise, direct one-paragraph commander's brief.
 *
 * Runs last (order 99) so all other widget data is available in context.
 * The widget receives the full sitrep context assembled by the orchestrator.
 * opt-in (defaultEnabled: false) — user must enable in CONFIG.
 *
 * BYOK: uses the user's Claude API key (Haiku by default — fast and cheap).
 */
import { complete } from '../lib/claude.js';
import { t } from '../lib/i18n.js';

const SYSTEM = `You are BROVIS, a no-nonsense personal intelligence officer.
Your job is to deliver a morning brief: one tight paragraph, plain prose, no bullet points, no markdown.
Lead with the most operationally relevant fact (weather if they need to go outside, a critical market move, a calendar conflict).
Speak directly to the commander by name if provided. Be sharp, not chatty.
Never say "Good morning" or use pleasantries. Never mention that you are an AI.`;

export default {
  id: 'morning-brief',
  name: 'Morning Brief',
  requiredKeys: ['claude'],
  defaultEnabled: false,
  needsContext: true,   // fetch(config, sitrepContext) — runs after base widgets
  order: 99,

  /**
   * @param {object} config  — full BROVIS config
   * @param {object} context — sitrep data: { weather, news, markets, verse, calendar }
   *                           Populated by the orchestrator before calling fetch.
   */
  async fetch(config, context = {}) {
    const name = config.user?.name || 'Commander';
    const parts = [];

    if (context.weather) {
      const w = context.weather;
      parts.push(`Weather: ${w.temp}, ${w.condition}, humidity ${w.humidity}, wind ${w.wind}.`);
      if (w.forecast?.length) {
        const f = w.forecast.map(d => `${d.day} ${d.high}/${d.low} ${d.condition}`).join('; ');
        parts.push(`Forecast: ${f}.`);
      }
    }

    if (context.markets?.length) {
      const highlights = context.markets
        .filter(m => m.change != null)
        .sort((a, b) => Math.abs(parseFloat(b.change)) - Math.abs(parseFloat(a.change)))
        .slice(0, 4)
        .map(m => `${m.label} ${m.price} (${m.change >= 0 ? '+' : ''}${m.change}%)`)
        .join(', ');
      if (highlights) parts.push(`Markets: ${highlights}.`);
    }

    if (context.calendar?.events?.length) {
      const events = context.calendar.events
        .map(e => e.title + (e.location ? ` at ${e.location}` : ''))
        .join('; ');
      parts.push(`Schedule: ${events}.`);
    } else if (context.calendar && !context.calendar.needsAuth) {
      parts.push('Schedule: Clear day.');
    }

    if (context.news?.length) {
      const headlines = context.news.map(a => a.title).join(' | ');
      parts.push(`Intel: ${headlines}.`);
    }

    if (context.verse) {
      parts.push(`Verse: "${context.verse.text.trim()}" — ${context.verse.reference}.`);
    }

    if (!parts.length) {
      parts.push(t('widget.brief.nodata'));
    }

    const prompt = `Commander: ${name}\n\n${parts.join('\n')}\n\nDeliver the morning brief.`;

    return complete({
      system: SYSTEM,
      prompt,
      maxTokens: 200,
      temperature: 0.5,
      cacheSystemPrompt: true  // 90% savings on system prompt tokens for 5 minutes
    });
  },

  render(text) {
    return `
      <div class="sitrep-section morning-brief">
        <div class="sitrep-section-title">
          ${t('widget.brief.name')}
          <span class="claude-badge" title="Generated by Claude · Anthropic">
            <svg class="claude-icon" viewBox="0 0 24 24" aria-hidden="true">
              <path d="M13.827 3.52l8.123 14.069a1.45 1.45 0 0 1-1.256 2.179H3.306a1.45 1.45 0 0 1-1.256-2.179L10.173 3.52a1.946 1.946 0 0 1 3.654 0z"/>
            </svg>
            Claude
          </span>
        </div>
        <p class="brief-text">${escapeHtml(text)}</p>
      </div>
    `;
  }
};

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}
